### ISSUE TITLE
请问wp-json文件夹在哪里？

### ISSUE THREAD

**Issue by StarDream521** [qinvz/Qinmeiorg#10]
我下了很多版本（最新版，4.9.4 4.9 以及古老版本）都没有这个文件夹 
您的包里也没用安装教程上写着 （在域名后面加上/wp-json/wp/v2/访问能看到下面的这些信息就代表没问题了）
但是wp程序里面有wp-json文件夹呀
请求帮助！

**Comment by Qinmei** [comment]
让你访问这个链接, 不是文件夹

**Comment by StarDream521** [comment]
我检测了伪静态 OK了！
