### ISSUE TITLE
大佬前端项目分享或者出售吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [qinvz/Qinmeiorg#3]
如果价格不高  可以入手

**Comment by Qinmei** [comment]
正在写react 的简易版主题, 过一段时间就能放出来了, 届时欢迎体验使用

**Comment by Yakumo-Yukari** [comment]
> 正在写react 的简易版主题, 过一段时间就能放出来了, 届时欢迎体验使用

好的  大概什么时候可以出来

**Comment by Qinmei** [comment]
一到两周吧,大致功能已经写好了

**Comment by Yakumo-Yukari** [comment]
> 一到两周吧,大致功能已经写好了

好的  麻烦 到时候通知一下
