### ISSUE TITLE
请问如何添加动漫？

### ISSUE THREAD

**Issue by lurenJBD** [qinvz/Qinmeiorg#6]
在添加动漫那一页里怎么都保存不了信息，获取豆瓣信息的按钮也没反应。我使用的是qinpress2.0。
系统环境使用的是WP5.2.1  Nignx1.5.1  Mysql5.7  PHP7.1
还请大佬高抬贵手了。

![Inked20190617202024_LI](https://user-images.githubusercontent.com/31967654/59604191-04709e00-913e-11e9-87e2-8c40ea121bf7.jpg)
![Inked20190617202048_LI](https://user-images.githubusercontent.com/31967654/59604198-063a6180-913e-11e9-9d32-dc1a55a32827.jpg)

**Comment by Qinmei** [comment]
豆瓣官方API已经GG了, 接口也获取不到信息

**Comment by lurenJBD** [comment]
那请问要如何才能保存添加的信息呢？集数添加也是会丢失的。

**Comment by Qinmei** [comment]
用4.9版本, 或者换回经典编辑器, 最新的编辑器有点不兼容

**Comment by mqdlzh** [comment]
谢谢大佬！
![20190620141133](https://user-images.githubusercontent.com/31967654/59825004-58110080-9365-11e9-8bc3-85d5a139790c.png)
切换回经典编辑器是指这样吗？

**Comment by lurenJBD** [comment]
非常感谢大佬的作品！
![20190620141133](https://user-images.githubusercontent.com/31967654/59829120-27ce5f80-936f-11e9-818d-3eb449bd1ac9.png)
这个提示我查了一下是和PHP版本有关的，请问是不是换成PHP5.6就解决了？如果不想换，是否有其他办法？

**Comment by Qinmei** [comment]
关闭php的错误提示就行
